### ISSUE TITLE
Problem beim Lesen der vendor Kennung

### ISSUE THREAD

**Issue by Wopfi** [staircaseblog/uvr16x2logging#1]
Da ich keine bessere Möglichkeit gefunden habe, Kontakt aufzunehmen, hab ich mal schnell eine Issue aufgemacht.

Meine System: Raspberry Pi 2 mit dem PiCAN 2 Modul. Am CAN Bus hängen zwei UVR1611 und ein BL-NET. Wenn ich das Script starte, werden die Node IDs richtig erkannt, aber beim Versuch die vendor Kennung der ersten UVR1611 zu lesen, gibt es einen Fehler.

```
[1L, 2L, 10L]
Traceback (most recent call last):
  File "./uvrlogger.py", line 386, in <module>
    ret = pruefeUVR(cob_id)
  File "./uvrlogger.py", line 45, in pruefeUVR
    vendor = node.sdo[0x1018][0x01]
  File "/home/pi/.local/lib/python2.7/site-packages/canopen/sdo.py", line 155, in __getitem__
    entry = self.od[index]
  File "/home/pi/.local/lib/python2.7/site-packages/canopen/objectdictionary/__init__.py", line 66, in __getitem__
    return self.names.get(index) or self.indices[index]
KeyError: 4120

```

Leider hab ich überhaupt keine Erfahrung mit dem canopen Modul oder mit dem canopen Protokoll selbst, deshalb bin ich aus dem Fehler nicht wirklich schlau geworden.

**Comment by staircaseblog** [comment]
Wir koennten telefonieren. Kommt der fehler ständig?

Am 11.09.2017 9:56 nachm. schrieb "Wopfi" <notifications@github.com>:

Da ich keine bessere Möglichkeit gefunden habe, Kontakt aufzunehmen, hab
ich mal schnell eine Issue aufgemacht.

Meine System: Raspberry Pi 2 mit dem PiCAN 2 Modul. Am CAN Bus hängen zwei
UVR1611 und ein BL-NET. Wenn ich das Script starte, werden die Node IDs
richtig erkannt, aber beim Versuch die vendor Kennung der ersten UVR1611 zu
lesen, gibt es einen Fehler.
[1L, 2L, 10L] ID: 1 Traceback (most recent call last): File
"./uvrlogger.py", line 386, in <module> ret = pruefeUVR(cob_id) File
"./uvrlogger.py", line 45, in pruefeUVR vendor = node.sdo[0x1018][0x01]
File "/home/pi/.local/lib/python2.7/site-packages/canopen/sdo.py", line
155, in __getitem__ entry = self.od[index] File
"/home/pi/.local/lib/python2.7/site-packages/canopen/objectdictionary/__init__.py",
line 66, in __getitem__ return self.names.get(index) or self.indices[index]
KeyError: 4120
Leider hab ich überhaupt keine Erfahrung mit dem canopen Modul oder mit dem
canopen Protokoll selbst, deshalb bin ich aus dem Fehler nicht wirklich
schlau geworden.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/staircaseblog/uvr16x2logging/issues/1>, or mute the
thread
