### ISSUE TITLE
Only issues hope someone can help !?

### ISSUE THREAD

**Issue by Gamerios** [staircaseblog/uvr16x2logging#2]
Hello

We have the **UVR 16x2**
**and a PI3 and CAN MCP2515**

Get with candump messages but with your **python uvrlogger.py**

**We get only after start this errors:**

Traceback (most recent call last):
  File "uvrlogger.py", line 366, in <module>
    network.scanner.search()
  File "/usr/local/lib/python2.7/dist-packages/canopen/network.py", line 262, in                                       search
    self.network.send_message(0x600 + node_id, sdo_req)
  File "/usr/local/lib/python2.7/dist-packages/canopen/network.py", line 164, in                                       send_message
    self.bus.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/can/interfaces/socketcan/socketca                                      n_ctypes.py", line 134, in send
    raise can.CanError("can.socketcan.ctypes failed to transmit")
can.CanError: can.socketcan.ctypes failed to transmit**

**Searched at google etc not find how tofix ort what the problem ist.**

**Hope someone or you the creator / dev can help thanks:**

**Comment by staircaseblog** [comment]
The can if is up and running?


Am 27.01.2018 12:42 vorm. schrieb "Gamerios" <notifications@github.com>:

**Comment by Gamerios** [comment]
@staircaseblog 
> The can if is up and running?


**pi@raspberrypi:~ $ ifconfig**
**can0: flags=193<UP,RUNNING,NOARP>  mtu 16**
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 1044  bytes 5522 (5.3 KiB)
        RX errors 0  dropped 22  overruns 0  frame 0
        TX packets 26  bytes 208 (208.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0




**When i send at CAN to UVR16x2 nothing all 10 secounds or so i get:**

 can0  701   [1]  05
  can0  701   [8]  05 87 01 00 F4 EC 4D 35
  can0  100   [6]  30 E6 7F 00 9D 30
  can0  1C1   [8]  01 00 01 01 00 00 00 00



**And when send**
cansend can0 601#4000100000000000

**I get this back:**
  can0  601   [8]  40 00 10 00 00 00 00 00
  can0  581   [8]  80 00 10 00 00 00 02 06




**so i think all is ok or not ?  or i missed something .** 
 is my first time at RPI3 with CAN neevr used can before also nt in car but want to.

**RPI3 i done much project already with it**

**Comment by Gamerios** [comment]
**Also you missed to upload the sample_uvr.eds** 


**Can you please upload all files that are needed ?**

Because:
  raise KeyError("%s was not found in Object Dictionary" % name)
KeyError: '0x1018 was not found in Object Dictionary'


and much more errors i try fix in your .py file but i think there arte many missing things. 


I have all installed canopen etc but things that are needed / you missed !?  i not have :(

**Comment by Gamerios** [comment]
I got most now 2 work because need fix / change many things in th e.py file of you.


**Have you an update of your script ?


BEcause no Energy or KW or KW/H  and other things are in from can port !?


Regards**
